version: "3.8"
services:
  phorge:
    build: .
    image: nicodoggie/phorge
    expose: [9000]
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./phorge:/srv/phorge:ro
      - ./arcanist:/srv/arcanist:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/docker.conf:/etc/nginx/conf.d/docker.conf:ro
  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=phorgetest
